[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js函数配置 - 优化性能
[functions]
  external_node_modules = ["openai", "axios", "zod"]
  node_bundler = "esbuild"
  # 增加内存限制
  memory = 1024
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

