[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js函数配置
[functions]
  external_node_modules = ["openai", "axios", "zod"]
  node_bundler = "esbuild"

# 环境变量 - 函数超时
[context.production.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
  NETLIFY_FUNCTIONS_TIMEOUT = "60"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

